# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{soapbox}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe Coyne", "Killit Creative"]
  s.date = %q{2011-07-27}
  s.description = %q{manage pages, users, permissions, settings, analytics, files, users, and extend}
  s.email = %q{gabe@killitcreative.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/admin_controller.rb",
    "app/controllers/admin/analytics_controller.rb",
    "app/controllers/admin/attachments_controller.rb",
    "app/controllers/admin/categories_controller.rb",
    "app/controllers/admin/comments_controller.rb",
    "app/controllers/admin/contents_controller.rb",
    "app/controllers/admin/galleries_controller.rb",
    "app/controllers/admin/gallery_images_controller.rb",
    "app/controllers/admin/groups_controller.rb",
    "app/controllers/admin/images_controller.rb",
    "app/controllers/admin/menu_items_controller.rb",
    "app/controllers/admin/menus_controller.rb",
    "app/controllers/admin/pages_controller.rb",
    "app/controllers/admin/plugins_controller.rb",
    "app/controllers/admin/redirects_controller.rb",
    "app/controllers/admin/settings_controller.rb",
    "app/controllers/admin/users_controller.rb",
    "app/controllers/admin/versions_controller.rb",
    "app/controllers/application_controller.rb",
    "app/controllers/attachments_controller.rb",
    "app/controllers/categories_controller.rb",
    "app/controllers/comments_controller.rb",
    "app/controllers/groups_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/controllers/plugins_controller.rb",
    "app/controllers/redirects_controller.rb",
    "app/controllers/settings_controller.rb",
    "app/controllers/sitemap_controller.rb",
    "app/helpers/content_helper.rb",
    "app/helpers/layout_helper.rb",
    "app/helpers/menu_helper.rb",
    "app/helpers/page_helper.rb",
    "app/helpers/plugin_helper.rb",
    "app/helpers/soapbox_helper.rb",
    "app/models/attachment.rb",
    "app/models/content.rb",
    "app/models/gallery.rb",
    "app/models/gallery_image.rb",
    "app/models/group.rb",
    "app/models/membership.rb",
    "app/models/menu.rb",
    "app/models/menu_item.rb",
    "app/models/page.rb",
    "app/models/permission.rb",
    "app/models/plugin.rb",
    "app/models/redirect.rb",
    "app/models/setting.rb",
    "app/models/soapbox/attachment.rb",
    "app/models/soapbox/content.rb",
    "app/models/soapbox/gallery.rb",
    "app/models/soapbox/gallery_image.rb",
    "app/models/soapbox/group.rb",
    "app/models/soapbox/membership.rb",
    "app/models/soapbox/menu.rb",
    "app/models/soapbox/menu_item.rb",
    "app/models/soapbox/page.rb",
    "app/models/soapbox/permission.rb",
    "app/models/soapbox/plugin.rb",
    "app/models/soapbox/redirect.rb",
    "app/models/soapbox/setting.rb",
    "app/models/soapbox/user.rb",
    "app/models/user.rb",
    "app/views/admin/analytics/index.html.erb",
    "app/views/admin/attachments/_image.html.erb",
    "app/views/admin/attachments/form.html.erb",
    "app/views/admin/attachments/index.html.erb",
    "app/views/admin/categories/form.html.erb",
    "app/views/admin/categories/index.html.erb",
    "app/views/admin/comments/form.html.erb",
    "app/views/admin/comments/index.html.erb",
    "app/views/admin/galleries/_image.html.erb",
    "app/views/admin/galleries/_manager.html.erb",
    "app/views/admin/galleries/form.html.erb",
    "app/views/admin/galleries/index.html.erb",
    "app/views/admin/groups/form.html.erb",
    "app/views/admin/groups/index.html.erb",
    "app/views/admin/menu_items/form.html.erb",
    "app/views/admin/menus/_item.html.erb",
    "app/views/admin/menus/form.html.erb",
    "app/views/admin/menus/index.html.erb",
    "app/views/admin/pages/form.html.erb",
    "app/views/admin/pages/index.html.erb",
    "app/views/admin/pages/link_list.html.erb",
    "app/views/admin/plugins/form.html.erb",
    "app/views/admin/plugins/index.html.erb",
    "app/views/admin/redirects/form.html.erb",
    "app/views/admin/redirects/index.html.erb",
    "app/views/admin/settings/form.html.erb",
    "app/views/admin/settings/index.html.erb",
    "app/views/admin/shared/_form_buttons.html.erb",
    "app/views/admin/shared/_form_errors.html.erb",
    "app/views/admin/shared/_list.html.erb",
    "app/views/admin/shared/_list_footer.html.erb",
    "app/views/admin/shared/_list_toolbar.html.erb",
    "app/views/admin/shared/_tag_manager.html.erb",
    "app/views/admin/shared/order.html.erb",
    "app/views/admin/shared/tree.html.erb",
    "app/views/admin/shared/wysiwyg.html.erb",
    "app/views/admin/users/form.html.erb",
    "app/views/admin/users/index.html.erb",
    "app/views/admin/versions/index.html.erb",
    "app/views/devise/confirmations/new.html.erb",
    "app/views/devise/mailer/confirmation_instructions.html.erb",
    "app/views/devise/mailer/reset_password_instructions.html.erb",
    "app/views/devise/mailer/unlock_instructions.html.erb",
    "app/views/devise/passwords/edit.html.erb",
    "app/views/devise/passwords/new.html.erb",
    "app/views/devise/registrations/edit.html.erb",
    "app/views/devise/registrations/new.html.erb",
    "app/views/devise/sessions/new.html.erb",
    "app/views/devise/shared/_links.erb",
    "app/views/devise/unlocks/new.html.erb",
    "app/views/galleries/_nivo_slider.html.erb",
    "app/views/galleries/_pretty_photo.html.erb",
    "app/views/groups/index.html.erb",
    "app/views/groups/show.html.erb",
    "app/views/layouts/_admin_toolbar.html.erb",
    "app/views/layouts/_admin_top_nav.html.erb",
    "app/views/layouts/_head.html.erb",
    "app/views/layouts/admin.html.erb",
    "app/views/layouts/admin_blank.html.erb",
    "app/views/layouts/login.html.erb",
    "app/views/pages/error_404.html.erb",
    "app/views/pages/index.html.erb",
    "app/views/pages/templates/default.html.erb",
    "app/views/sitemap/sitemap.rxml",
    "config/permissions.yml.template",
    "config/routes.rb",
    "init.rb",
    "install.rb",
    "lib/generators/soapbox_scaffold/soapbox_scaffold_generator.rb",
    "lib/generators/soapbox_scaffold/templates/admin_controller.rb",
    "lib/generators/soapbox_scaffold/templates/controller.rb",
    "lib/generators/soapbox_scaffold/templates/migration.rb",
    "lib/generators/soapbox_scaffold/templates/model.rb",
    "lib/generators/soapbox_scaffold/templates/views/admin/form.html.erb",
    "lib/generators/soapbox_scaffold/templates/views/admin/index.html.erb",
    "lib/generators/soapbox_scaffold/templates/views/index.html.erb",
    "lib/generators/soapbox_scaffold/templates/views/show.html.erb",
    "lib/paperclip.rb",
    "lib/soapbox.rb",
    "lib/states.rb",
    "test/helper.rb",
    "test/test_soapbox.rb"
  ]
  s.homepage = %q{http://github.com/gabecoyne/soapbox}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails CMS by Killit Creative}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<devise>, ["= 1.1.2"])
      s.add_runtime_dependency(%q<formtastic>, ["= 1.2.3"])
      s.add_runtime_dependency(%q<polypaperclip>, ["= 0.1.8"])
      s.add_runtime_dependency(%q<paper_trail>, ["~> 2"])
      s.add_runtime_dependency(%q<will_paginate>, ["= 2.3.15"])
      s.add_runtime_dependency(%q<acts-as-taggable-on>, [">= 0"])
      s.add_runtime_dependency(%q<friendly_id>, ["~> 3.1"])
      s.add_runtime_dependency(%q<inherited_resources>, ["= 1.2.2"])
      s.add_runtime_dependency(%q<acts_as_indexed>, [">= 0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_tree>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_list>, [">= 0"])
      s.add_runtime_dependency(%q<garb>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_dependency(%q<devise>, ["= 1.1.2"])
      s.add_dependency(%q<formtastic>, ["= 1.2.3"])
      s.add_dependency(%q<polypaperclip>, ["= 0.1.8"])
      s.add_dependency(%q<paper_trail>, ["~> 2"])
      s.add_dependency(%q<will_paginate>, ["= 2.3.15"])
      s.add_dependency(%q<acts-as-taggable-on>, [">= 0"])
      s.add_dependency(%q<friendly_id>, ["~> 3.1"])
      s.add_dependency(%q<inherited_resources>, ["= 1.2.2"])
      s.add_dependency(%q<acts_as_indexed>, [">= 0"])
      s.add_dependency(%q<aws-s3>, [">= 0"])
      s.add_dependency(%q<acts_as_tree>, [">= 0"])
      s.add_dependency(%q<acts_as_list>, [">= 0"])
      s.add_dependency(%q<garb>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
    s.add_dependency(%q<devise>, ["= 1.1.2"])
    s.add_dependency(%q<formtastic>, ["= 1.2.3"])
    s.add_dependency(%q<polypaperclip>, ["= 0.1.8"])
    s.add_dependency(%q<paper_trail>, ["~> 2"])
    s.add_dependency(%q<will_paginate>, ["= 2.3.15"])
    s.add_dependency(%q<acts-as-taggable-on>, [">= 0"])
    s.add_dependency(%q<friendly_id>, ["~> 3.1"])
    s.add_dependency(%q<inherited_resources>, ["= 1.2.2"])
    s.add_dependency(%q<acts_as_indexed>, [">= 0"])
    s.add_dependency(%q<aws-s3>, [">= 0"])
    s.add_dependency(%q<acts_as_tree>, [">= 0"])
    s.add_dependency(%q<acts_as_list>, [">= 0"])
    s.add_dependency(%q<garb>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

